package com.example.learnandroid.activity

const val BUTTON_NAME_TEST = "测试"
const val BUTTON_NAME_CLEAR_RENDERER = "背景色01"
const val BUTTON_NAME_TRIANGLE_RENDERER = "三角形02"
const val BUTTON_NAME_MATRIX_TRIANGLE_RENDERER= "等腰三角形03"
const val BUTTON_NAME_COLOR_TRIANGLE_RENDERER = "彩色三角形和矩形04"
const val BUTTON_NAME_CIRCLE_RENDERER = "圆形05"
const val BUTTON_NAME_POLYGON_RENDERER = "索引法多边形06"
const val BUTTON_NAME_CUBE_RENDERER = "立方体07"
const val BUTTON_NAME_SQUARE_TEXTURE_RENDERER = "矩形纹理贴图08"
const val BUTTON_NAME_RECYCLER_VIEW = "RecyclerView"
const val BUTTON_NAME_PAG_VIEW = "PagView"
const val BUTTON_NAME_LOTTIE_VIEW = "LottieView"
const val BUTTON_NAME_CAMERA1 = "Camera1"
const val BUTTON_NAME_SHADOW_FRAME_LAYOUT = "ShadowFrameLayout"
const val BUTTON_NAME_WEBVIEW = "WebView"
const val BUTTON_CANVAS = "Canvas"